#include "page.h"

#include <string.h>

/* generated by tools/embed.c into build/ (see Makefile) */
#include "asset_hljs_js.h"
#include "asset_hljs_css.h"

/* Compact GitHub-flavored stylesheet. Colors ride on CSS variables so the
 * dark theme is a single media-query block. */
static const char BASE_CSS[] =
    ":root{--bg:#fff;--fg:#1f2328;--muted:#59636e;--border:#d1d9e0;"
    "--code-bg:#f6f8fa;--accent:#0969da;--tr-alt:#f6f8fa;--shadow:rgba(0,0,0,.12)}"
    "@media(prefers-color-scheme:dark){:root{--bg:#0d1117;--fg:#f0f6fc;"
    "--muted:#9198a1;--border:#3d444d;--code-bg:#151b23;--accent:#4493f8;"
    "--tr-alt:#151b23;--shadow:rgba(0,0,0,.5)}}"
    "*{box-sizing:border-box}"
    "html,body{margin:0;padding:0;background:var(--bg);color:var(--fg)}"
    "body{font:16px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,"
    "Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji'}"
    ".content{max-width:900px;margin:0 auto;padding:32px 28px}"
    ".content-wide{max-width:none;margin:0;padding:16px}"
    "h1,h2,h3,h4,h5,h6{margin:24px 0 12px;font-weight:600;line-height:1.25}"
    "h1{font-size:2em;padding-bottom:.3em;border-bottom:1px solid var(--border)}"
    "h2{font-size:1.5em;padding-bottom:.3em;border-bottom:1px solid var(--border)}"
    "h3{font-size:1.25em}h4{font-size:1em}"
    "h5{font-size:.875em}h6{font-size:.85em;color:var(--muted)}"
    "p,ul,ol,blockquote,table,pre{margin:0 0 16px}"
    "a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}"
    "code,pre,kbd{font-family:ui-monospace,SFMono-Regular,'SF Mono',Menlo,"
    "Consolas,'Liberation Mono',monospace}"
    "code{font-size:.875em;background:var(--code-bg);padding:.2em .4em;"
    "border-radius:6px}"
    "pre{background:var(--code-bg);border-radius:6px;padding:16px;"
    "overflow:auto;line-height:1.45}"
    "pre code{background:none;padding:0;font-size:.875em;display:block}"
    "blockquote{padding:0 1em;color:var(--muted);"
    "border-left:.25em solid var(--border)}"
    "ul,ol{padding-left:2em}li+li{margin-top:.25em}"
    "li.task{list-style:none;margin-left:-1.5em}"
    "hr{border:0;height:2px;background:var(--border);margin:24px 0}"
    "table{border-collapse:collapse;display:block;overflow-x:auto;"
    "max-width:100%}"
    "th,td{border:1px solid var(--border);padding:6px 13px}"
    "th{font-weight:600;background:var(--tr-alt)}"
    "tbody tr:nth-child(2n){background:var(--tr-alt)}"
    "img{max-width:100%}"
    /* full-window image viewer */
    ".imgview{display:flex;min-height:100vh;align-items:center;"
    "justify-content:center;padding:20px}"
    ".imgview img{max-width:100%;max-height:calc(100vh - 40px);"
    "box-shadow:0 4px 24px var(--shadow);border-radius:2px}"
    /* data tables (csv) */
    ".datatable{padding:0}"
    ".datatable table{display:table;width:100%;font-size:.875em}"
    ".datatable thead th{position:sticky;top:0;background:var(--bg);"
    "box-shadow:0 1px 0 var(--border)}"
    ".rownum{color:var(--muted);text-align:right;user-select:none}"
    /* file header bar used by error/binary pages */
    ".filehead{color:var(--muted);font-size:.875em;margin-bottom:24px}"
    ".errbox{max-width:560px;margin:15vh auto 0;text-align:center}"
    ".errbox .icon{font-size:56px;margin-bottom:8px}"
    ".errbox .detail{color:var(--muted);font-size:.875em;margin-top:8px}";

void page_begin(sb *s, const char *title, unsigned flags) {
    sb_append(s, "<!DOCTYPE html><html><head><meta charset=\"utf-8\">"
                 "<meta name=\"viewport\" "
                 "content=\"width=device-width,initial-scale=1\"><title>");
    sb_append_html(s, title, strlen(title));
    sb_append(s, "</title><style>");
    sb_append(s, BASE_CSS);
    sb_append(s, "</style>");
    if (flags & PAGE_HLJS) {
        sb_append(s, "<style>");
        sb_append_n(s, (const char *)ASSET_HLJS_CSS, ASSET_HLJS_CSS_len);
        sb_append(s, "</style>");
    }
    sb_append(s, "</head><body>");
}

void page_end(sb *s, unsigned flags) {
    if (flags & PAGE_HLJS) {
        sb_append(s, "<script>");
        sb_append_n(s, (const char *)ASSET_HLJS_JS, ASSET_HLJS_JS_len);
        sb_append(s, "</script><script>"
                     "document.querySelectorAll('pre code').forEach(el=>{"
                     "const m=el.className.match(/language-(\\S+)/);"
                     "if(m&&!hljs.getLanguage(m[1])){el.className='';}"
                     "hljs.highlightElement(el);});"
                     "</script>");
    }
    sb_append(s, "</body></html>");
}

char *page_error(const char *title, const char *message, const char *detail) {
    sb s;
    sb_init(&s);
    page_begin(&s, title, 0);
    sb_append(&s, "<div class=\"errbox\"><div class=\"icon\">&#9888;</div><h2>");
    sb_append_html(&s, message, strlen(message));
    sb_append(&s, "</h2><div class=\"detail\">");
    sb_append_html(&s, detail ? detail : "", detail ? strlen(detail) : 0);
    sb_append(&s, "</div></div>");
    page_end(&s, 0);
    return sb_take(&s);
}
